# This workflow will build and push a new container image to GCP GKE
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an Artifact Registry Docker repository to store your images.
#    For example: gcloud artifacts repositories create cjot-stocktrader-pipeline1-repository \
#  --repository-format=docker \
#  --location=us-central1
#    Replace the value of `GCP_REPOSITORY` in the workflow below with your repository's name.
#    Replace the value of `gcp-region` in the workflow below with your repository's region.
#
# 2. Create a Cloud Build Trigger to launch the CI process.
#
# 3. Store your ECS task definition as a JSON file in your repository. ???
#

#steps:

# Specify the entrypoint for the maven image; print the build tool version
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['--version']

# Run test
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['test']

# Package application
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true','-Dmaven.test.skip=true']

# Build a docker container and push it to GCP repository
- name: 'gcr.io/cloud-builders/docker'
  id: Build
#    args: [ 'build', '-t', 'us-west1-docker.pkg.dev/cloud-engagement-hub/cjot-stocktrader-repo/broker:latest', '.' ]
  args: [ 'build', '-t', 'us-west1-docker.pkg.dev/cloud-engagement-hub/cjot-stocktrader-repo/broker:$SHORT_SHA', '.' ]
images:
- 'us-west1-docker.pkg.dev/cloud-engagement-hub/cjot-stocktrader-repo/broker:$SHORT_SHA'
#- 'us-west1-docker.pkg.dev/cloud-engagement-hub/cjot-stocktrader-repo/broker:latest'
timeout: 3600s