apiVersion: operators.ibm.com/v1
kind: StockTrader
metadata:
  name: ceh
spec:
  global:
    auth: basic
    healthCheck: true
    ingress: false
    istio: false
    istioNamespace: mesh
    route: false
    traceSpec: "*=info"
    jsonLogging: false
    disableLogFiles: false
    monitoring: true
    specifyCerts: true
    certs: |
      -----BEGIN CERTIFICATE-----
      MIINlTCCDH2gAwIBAgIQA1OXnI5PL8iJCejmERiIHTANBgkqhkiG9w0BAQsFADBP
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMSkwJwYDVQQDEyBE
      aWdpQ2VydCBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTAeFw0yMTAyMjIwMDAwMDBa
      Fw0yMjAzMjUyMzU5NTlaMIGnMQswCQYDVQQGEwJVUzEPMA0GA1UECBMGS2Fuc2Fz
      MRYwFAYDVQQHEw1PdmVybGFuZCBQYXJrMTQwMgYDVQQKEytJTlRFUk5BVElPTkFM
      IEJVU0lORVNTIE1BQ0hJTkVTIENPUlBPUkFUSU9OMTkwNwYDVQQDDDAqLmJwZTYw
      cGJkMDFvaW5nZTRwc2QwLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWQwggEiMA0G
      CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCv0ui2hmxME58o+u6At34nSBXkcgqM
      LYY2T0gjXezi85mvdEpwwQhl0jqdTOZYuIIpOYmpslEWB709lzhyWGqgnKP+DasE
      ZTJHpKLeangLW84jWSpvVeyZ+yR4XTDntaTPysA0MB7UN3oeG5JhHTQOTjn12sA7
      DIF5G5pfRBFK5gZFD74RO7tPsbpMeWx+99Lf4uHLvwkNziHPNshhVCRtclPKONv0
      M91wXiIcsTBXizqkspfldVtBAE2+c/HhJiM8mBzflFAAvtMgRxNHuxfiKphXgO1N
      1mRbmzrzS4e3ibbb2Zf/SIgFD55uHq6h8vsmElFQTB44Cg0zNpaxrkMlAgMBAAGj
      ggoSMIIKDjAfBgNVHSMEGDAWgBS3a6LqqKqEjHnqtNoPmLLFlXa59DAdBgNVHQ4E
      FgQUGCOFTuIXJJa/xOcEc5qlhEk5VvUwggc5BgNVHREEggcwMIIHLIIwKi5icGU2
      MHBiZDAxb2luZ2U0cHNkMC5kYXRhYmFzZXMuYXBwZG9tYWluLmNsb3VkgjgqLmJw
      ZTYwcGJkMDFvaW5nZTRwc2QwLnByaXZhdGUuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZII4Ki5iczJpcGE3dzB1djl0c29taTlpZy5wcml2YXRlLmRhdGFiYXNlcy5h
      cHBkb21haW4uY2xvdWSCMCouYnMyaXBhN3cwdXY5dHNvbWk5aWcuZGF0YWJhc2Vz
      LmFwcGRvbWFpbi5jbG91ZII4Ki5iczJpcG1idDBpZmxkOHJkYzl1MC5wcml2YXRl
      LmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnMyaXBtYnQwaWZsZDhyZGM5
      dTAuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5iczJpbzkwbDA4a3FiMW9k
      OGxjZy5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnMyaW85
      MGwwOGtxYjFvZDhsY2cuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5icnQ5
      ZDA0ZjBjbXFlYjh1Nzc0MC5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xv
      dWSCMCouYnJ0OWQwNGYwY21xZWI4dTc3NDAuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZII4Ki5iczJpcHI4czA3YjdiZ20xdGE4MC5wcml2YXRlLmRhdGFiYXNlcy5h
      cHBkb21haW4uY2xvdWSCMCouYnMyaXByOHMwN2I3YmdtMXRhODAuZGF0YWJhc2Vz
      LmFwcGRvbWFpbi5jbG91ZII4Ki5idHY1M2wwZjA1NDE4MzlvMXY0MC5wcml2YXRl
      LmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnR2NTNsMGYwNTQxODM5bzF2
      NDAuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5idWdxOXR1dzA4MW52ZTlu
      ZTE2MC5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnVncTl0
      dXcwODFudmU5bmUxNjAuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5idHYx
      cmVqZjBydGtwZDE2MnJnMC5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xv
      dWSCMCouYnR2MXJlamYwcnRrcGQxNjJyZzAuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZII4Ki5idHY1cDVmZDBjdDYzODNxZnRkZy5wcml2YXRlLmRhdGFiYXNlcy5h
      cHBkb21haW4uY2xvdWSCMCouYnR2NXA1ZmQwY3Q2MzgzcWZ0ZGcuZGF0YWJhc2Vz
      LmFwcGRvbWFpbi5jbG91ZII4Ki5idHY0OGpjdzBwZGQ2ZjRubWd2Zy5wcml2YXRl
      LmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnR2NDhqY3cwcGRkNmY0bm1n
      dmcuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5idHYyczN0ZjBrbTR1c3Bv
      MXYzMC5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnR2MnMz
      dGYwa200dXNwbzF2MzAuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZII4Ki5idW5r
      bGFlZjBqazM0aXVmNml2Zy5wcml2YXRlLmRhdGFiYXNlcy5hcHBkb21haW4uY2xv
      dWSCMCouYnVua2xhZWYwamszNGl1ZjZpdmcuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZII4Ki5idjdjM282ZDB2ZmhydTNucGRzMC5wcml2YXRlLmRhdGFiYXNlcy5h
      cHBkb21haW4uY2xvdWSCMCouYnY3YzNvNmQwdmZocnUzbnBkczAuZGF0YWJhc2Vz
      LmFwcGRvbWFpbi5jbG91ZII4Ki5idjdlOHJiZjBzaHNsYm8wa3JzZy5wcml2YXRl
      LmRhdGFiYXNlcy5hcHBkb21haW4uY2xvdWSCMCouYnY3ZThyYmYwc2hzbGJvMGty
      c2cuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZIIwKi5jMDh1dDA3bDBwaW5jcGRs
      ZTg5MC5kYXRhYmFzZXMuYXBwZG9tYWluLmNsb3VkgjgqLmMwOHV0MDdsMHBpbmNw
      ZGxlODkwLnByaXZhdGUuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZIIwKi5icjM5
      YjRrZDBuaGNjM2pmZmJ0MC5kYXRhYmFzZXMuYXBwZG9tYWluLmNsb3VkgjgqLmJy
      MzliNGtkMG5oY2MzamZmYnQwLnByaXZhdGUuZGF0YWJhc2VzLmFwcGRvbWFpbi5j
      bG91ZDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
      BwMCMIGLBgNVHR8EgYMwgYAwPqA8oDqGOGh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNv
      bS9EaWdpQ2VydFRMU1JTQVNIQTI1NjIwMjBDQTEuY3JsMD6gPKA6hjhodHRwOi8v
      Y3JsNC5kaWdpY2VydC5jb20vRGlnaUNlcnRUTFNSU0FTSEEyNTYyMDIwQ0ExLmNy
      bDA+BgNVHSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3
      LmRpZ2ljZXJ0LmNvbS9DUFMwfQYIKwYBBQUHAQEEcTBvMCQGCCsGAQUFBzABhhho
      dHRwOi8vb2NzcC5kaWdpY2VydC5jb20wRwYIKwYBBQUHMAKGO2h0dHA6Ly9jYWNl
      cnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRMU1JTQVNIQTI1NjIwMjBDQTEuY3J0
      MAwGA1UdEwEB/wQCMAAwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdQApeb7wnjk5
      IfBWc59jpXflvld9nGAK+PlNXSZcJV3HhAAAAXfLZUkOAAAEAwBGMEQCIHWszBBW
      UaAnNbPWtNWo/MYCgUOmmfKOST4TthOgRruBAiAHrcR1a2K0VJstbNaYp+8dOhfM
      rGiKafcmjyvvPAkG/wB2AFGjsPX9AXmcVm24N3iPDKR6zBsny/eeiEKaDf7UiwXl
      AAABd8tlSWMAAAQDAEcwRQIgS1zYbxK0X5gVyiLbOTGL9EbmmxKwaLbxkqkg14aj
      reACIQDgRPZZQvZIW3V0tTXDek5WXOYce2Wb5oXhy4gGKvKytTANBgkqhkiG9w0B
      AQsFAAOCAQEAQnv7zROg6HtUM9/JvctOxnpPCKZlk7jFsjFvoL2rAXebg5et08uK
      uufC8lJ1+jO/9q4T+8ugd6c65SVOdG3EnL4wTv+pXcnbn55nRqtXs3SgyJcusdyx
      3XgTU8LYE9Ig7fIboveIeeEfTnE4XUBH3E63x7D74QYWRBMtJyTsZgoLr8T2FvYk
      euAsFH0gBe5PBUrsXMfF9z4J7Z+twM49cYqZf5gi9Ewl8Ikm7NZlPkJIxp+/T3NV
      kR1bArTyi7+7aBbP7DCSd5prmHPj3LEsXdPD0GtpfsRVjvPLbPNtyYylpt2CGKFg
      zngDAqDez0xH+lXeXo3l1CwdMllRctPk2A==
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIDDzCCAfegAwIBAgIJANEH58y2/kzHMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV
      BAMME0lCTSBDbG91ZCBEYXRhYmFzZXMwHhcNMTgwNjI1MTQyOTAwWhcNMjgwNjIy
      MTQyOTAwWjAeMRwwGgYDVQQDDBNJQk0gQ2xvdWQgRGF0YWJhc2VzMIIBIjANBgkq
      hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8lpaQGzcFdGqeMlmqjffMPpIQhqpd8qJ
      Pr3bIkrXJbTcJJ9uIckSUcCjw4Z/rSg8nnT13SCcOl+1to+7kdMiU8qOWKiceYZ5
      y+yZYfCkGaiZVfazQBm45zBtFWv+AB/8hfCTdNF7VY4spaA3oBE2aS7OANNSRZSK
      pwy24IUgUcILJW+mcvW80Vx+GXRfD9Ytt6PRJgBhYuUBpgzvngmCMGBn+l2KNiSf
      weovYDCD6Vngl2+6W9QFAFtWXWgF3iDQD5nl/n4mripMSX6UG/n6657u7TDdgkvA
      1eKI2FLzYKpoKBe5rcnrM7nHgNc/nCdEs5JecHb1dHv1QfPm6pzIxwIDAQABo1Aw
      TjAdBgNVHQ4EFgQUK3+XZo1wyKs+DEoYXbHruwSpXjgwHwYDVR0jBBgwFoAUK3+X
      Zo1wyKs+DEoYXbHruwSpXjgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
      AQEAJf5dvlzUpqaix26qJEuqFG0IP57QQI5TCRJ6Xt/supRHo63eDvKw8zR7tlWQ
      lV5P0N2xwuSl9ZqAJt7/k/3ZeB+nYwPoyO3KvKvATunRvlPBn4FWVXeaPsG+7fhS
      qsejmkyonYw77HRzGOzJH4Zg8UN6mfpbaWSsyaExvqknCp9SoTQP3D67AzWqb1zY
      doqqgGIZ2nxCkp5/FXxF/TMb55vteTQwfgBy60jVVkbF7eVOWCv0KaNHPF5hrqbN
      i+3XjJ7/peF3xMvTMoy35DcT3E2ZeSVjouZs15O90kI3k2daS2OHJABW0vSj4nLz
      +PQzp/B9cQmOO8dCe049Q3oaUA==
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIDfzCCAmegAwIBAgIBADANBgkqhkiG9w0BAQsFADB3MS0wKwYDVQQuEyRiYTY1
      ZDQ4Ny1mOThmLTQxZTYtYjY0YS1iYWI5YzgzNWI4Y2MxIzAhBgNVBAMTGkdvb2ds
      ZSBDbG91ZCBTUUwgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkG
      A1UEBhMCVVMwHhcNMjExMTE1MTgwNDMzWhcNMzExMTEzMTgwNTMzWjB3MS0wKwYD
      VQQuEyRiYTY1ZDQ4Ny1mOThmLTQxZTYtYjY0YS1iYWI5YzgzNWI4Y2MxIzAhBgNV
      BAMTGkdvb2dsZSBDbG91ZCBTUUwgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUs
      IEluYzELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
      AQCnHBBWJpCsANtswDwrTx/ORd2s9b9TgFD9nh9VVfK/KudiQSj+gPBvBe2m9oXq
      YjmLndC0XIjXTB1QV0ZAbfQuk/rSgr/zxV0wg5uFbo89GI2N8tj8mcR+0Axs9Xvi
      pQ4Ay+GtpHzPEiHOQQ3x+3MjnEbEo5/iMSYfYTeXShQj/0MF1Xr4YZ2aWnU5sxCv
      XxaVuOlIRkhAS1pSa7r15HsRn5PDruxsu2DPjQ7SXfp5jCfHmb3LllBpNxWY4U6o
      eUFhwDCyPz09FtGJtz3fsik70UO77NE5WUIjC7IS7BxLLx1RxPcb0B6wYeT3eesW
      ul2AxrdcymMdTMPMBer8A4gRAgMBAAGjFjAUMBIGA1UdEwEB/wQIMAYBAf8CAQAw
      DQYJKoZIhvcNAQELBQADggEBAA+azNsUT4YYlcFQZYUrxwxlJD5Ifj8rBs4Gv3QP
      dBHU2bz3qyFd+CQUINPBsSupdNOA3Ib7okyh5bd/hFDk/oKk2NB/7UywJ00IFRr+
      gc9VoWWUc/EPfnW90X2OkxnWzl/WxnoexJI8zAwpIg7sJvjvSHtb+bocNLI0TfyP
      7sqaEx9+Plu7EOqwv3GGjl+ZyIwqZqvVF+sXrVW5PM/gna5uyQJwCk+vv3Q9u4En
      fLmr8/f6gL0/lM2X02T2jxwB22wW5P3/DKOMQmC09FUa/flvMT46QdNR8n3bNINP
      0+rxwvvnBvZgEuMRePCrXYUfOPKNsdC5Cc70I9wylAmKanM=
      -----END CERTIFICATE-----

      -----BEGIN CERTIFICATE-----
      MIIDnTCCAoWgAwIBAgIBADANBgkqhkiG9w0BAQsFADCBhTEtMCsGA1UELhMkMmM3
      MmU2ZDEtMGViNi00YmNkLWIyMDMtOWNjOTZjNGU5MGEzMTEwLwYDVQQDEyhHb29n
      bGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVkaXMgU2VydmVyIENBMRQwEgYDVQQKEwtH
      b29nbGUsIEluYzELMAkGA1UEBhMCVVMwHhcNMjExMjAyMTcyNDE1WhcNMzExMTMw
      MTcyNTE1WjCBhTEtMCsGA1UELhMkMmM3MmU2ZDEtMGViNi00YmNkLWIyMDMtOWNj
      OTZjNGU5MGEzMTEwLwYDVQQDEyhHb29nbGUgQ2xvdWQgTWVtb3J5c3RvcmUgUmVk
      aXMgU2VydmVyIENBMRQwEgYDVQQKEwtHb29nbGUsIEluYzELMAkGA1UEBhMCVVMw
      ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCWG2nTivkiikq9wSTcXW8v
      aB7NqpI8NYDx/VPbwxb7v+wjy6ePDvu7uBXYUp659oSgyhcB61ed+dnvJk7241cz
      qilY+a9PuM2NJqmbum4DzB0A5srT1FcDFCij0J9eI1jpdCt65bvPajqVS85x3/vi
      Yc7ROy+Ehp3YtYTjtWH9aG9nGaWuyPzr5fudnh1JOQHRWFskzxj4hCAltNFlC85v
      RkEyS97M+uPaf/Hzh28YiVaYk1gUFfxenUvfv9sWmY3u4BZTCimqgIq4AM36WQqu
      inbzPjzR006LNgzS62Q/f7SIMz6dwlYtfg78ur5qubtOvrHUw4FtChve4rfhxaUb
      AgMBAAGjFjAUMBIGA1UdEwEB/wQIMAYBAf8CAQAwDQYJKoZIhvcNAQELBQADggEB
      AJSIG+/PIfcV8uM0SIA2Oq6FMYqi7M5OTVQSpi0GDXZIMg2J02Dp6VIOr2hG0z1e
      a5JwCT1MKx1q/KuRYLe3YWBC/X5lBKhYK9xyCF0BtrAMeNYUpDaxiWKyMTjUpLQV
      3t38t29Hi2zGwWR4DJTvdJFwDKo9t+2ClXJ1pg2FEgQyYiKpe3v0MJlDY+tEDFxR
      9iNx8KisOSuSWpPBxauKmVdNfg0uVpoUphyBShurrcWHioWUEl0kNsBzy03Te+WI
      zhUfkHm9cwhrNyMHXo3+wJFReKxXO6G5ZE0AuQdNS6Cgb51+I5I99+LiflVrG1yK
      ZcVXkqLlFoLYvOtZs1OqVHU=
      -----END CERTIFICATE-----

  database:
    kind: postgres
    db: postgres
    host: 10.6.64.3
    id: postgres
    password: umBkAwsPqidLxmt5
    port: 5432
    ssl: true
  ingress:
    address: <your proxy node IP>:443
  jwt:
    audience: stock-trader
    issuer: http://stock-trader.ibm.com
  kafka:
#   address: broker-1-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-4-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-3-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-0-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-2-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093,broker-5-63pby2k66qq17x9z.kafka.svc01.us-south.eventstreams.cloud.ibm.com:9093
#   apiKey: Vt3DoVpCvDE4xKs7WERkgODnWLoxR4ATpIwqevDiSJQd
#   user: token
    address: pkc-3w22w.us-central1.gcp.confluent.cloud:9092
    apiKey: +DhY73fmUizW/tygsQSb0aS8AyVkL8zbkxrw08wFnHGGQMivBAzHRWa/zN2moQGD
    accountTopic: account
    historyTopic: history
    portfolioTopic: portfolio
    user: 4LWFK4TDUYXNLIPB
  looper:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/looper
      tag: latest
    url: http://{{ .Release.Name }}-looper-service:9080/looper
  broker:
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: us-west1-docker.pkg.dev/cloud-engagement-hub/cjot-stocktrader-repo/broker
      tag: bt-nocache-1.0
    url: http://{{ .Release.Name }}-broker-service:9080/broker
  brokerCQRS:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/broker-cqrs
      tag: latest
    url: http://{{ .Release.Name }}-broker-cqrs-service:9080/brokerCQRS
  account:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/account
      tag: latest
    url: http://{{ .Release.Name }}-account-service:9080/account
  messaging:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/messaging
      tag: latest
    notification:
      url: http://{{ .Release.Name }}-notification-service:9080/notification
  cloudant:
    id: 878ff489-3ab9-4d2d-86db-016f19864439-bluemix
    password: 58819704e70bb791d81eb09847e8da2d69cb492ed4fe35a4e682e38c0785e5e9
    url: https://878ff489-3ab9-4d2d-86db-016f19864439-bluemix:58819704e70bb791d81eb09847e8da2d69cb492ed4fe35a4e682e38c0785e5e9@878ff489-3ab9-4d2d-86db-016f19864439-bluemix.cloudantnosqldb.appdomain.cloud
    apiKey: x5IiJ91ycorpEZJztgPCMQ9bQ26cQZwALO2Abgkn4XIT
    database: account
    collector: evidence
  collector:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/collector
      tag: latest
    url: http://{{ .Release.Name }}-collector-service:9080/collector
  ldap:
    baseDN: o=ibm.com
    host: bluepages.ibm.com
    port: 389
    realm: BluePages
  mongo:
    authDB: admin
    database: ibmclouddb
    ip: 915ce0b3-e08f-4aec-b58a-47e80442c6b4-0.blijs0dd0dcr4f55oehg.databases.appdomain.cloud
    port: 30926
    user: ibm_cloud_e0b8c9f6_e968_45d0_abc8_0de400862558
    password: 4f3d8806f907f21ba8da8eeef36d0099184c265ed9b266a836b73605a93187ef
  mq:
    channel: CLOUD.APP.SVRCONN
    host: qm1-4565.qm.us-south.mq.appdomain.cloud
    id: mqstocktrade
    password: NtrvEB4o4iQFrraGUdvgfoP40D-HdeFZ8qPFunsHBBkU
    port: 30341
    queue: LoyaltyLevelChange
    queueManager: QM1
  notificationSlack:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/notification-slack
      tag: latest
  notificationTwitter:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/notification-twitter
      tag: latest
  odm:
    id: odmAdmin
    password: odmAdmin
    url: https://odm-connect-cp4a.devops-prereqs-44-a01ee4194ed985a1e32b1d96fd4ae346-0000.us-east.containers.appdomain.cloud/DecisionService/rest/v1/ICP_Trader_Dev_1/determineLoyalty
  oidc:
    clientId: <your client id>
    clientSecret: <your client secret>
    discoveryUrl: <your discovery url>
  openwhisk:
    id: bc2b0a37-0554-4658-9ebe-ae068eb1aa22
    password: 45t2FZC1q1bv6OYUztZUjkYFaVNs5klaviHoE6gFvgEedu9akiE1YW6lChOxUgJb
    url: https://openwhisk.ng.bluemix.net/api/v1/namespaces/jalcorn%40us.ibm.com_dev/actions/PostLoyaltyLevelToSlack
  portfolio:
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: us-west1-docker.pkg.dev/cloud-engagement-hub/cjot-stocktrader-repo/portfolio
      tag: bt-nocache-1.0
    url: http://{{ .Release.Name }}-portfolio-service:9080/portfolio
  redis:
    cacheInterval: 60
    urlWithCredentials: rediss://10.6.65.3:6378
  s3:
    enabled: false
    bucket: stock-trader
    location: us
    endpointUrl: https://s3.us-east.cloud-object-storage.appdomain.cloud
    resourceInstanceId: >-
      crn:v1:bluemix:public:cloud-object-storage:global:a/b71ac2564ef0b98f1032d189795994dc:f7e4281d-a7f2-4923-8e6b-07f99ac93bbd::
    apiKey: YqfZRMwzGlzdA_fMLRaBMfvwjQ4UMu7lz_N_LzJcJwLM
  stockQuote:
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    apiConnect: https://api.us.apiconnect.ibmcloud.com/jalcornusibmcom-dev/sb/stocks
    iexApiKey: <your IEX API key>
    iexTrading: https://cloud.iexapis.com/stable/stock
    image:
      repository: ibmstocktrader/stock-quote
      tag: latest
    url: http://{{ .Release.Name }}-stock-quote-service:9080/stock-quote
  tradeHistory:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/trade-history
      tag: latest
    url: http://{{ .Release.Name }}-trade-history-service:9080/trade-history
  trader:
    enabled: true
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/trader
      tag: latest
  tradr:
    enabled: false
    replicas: 1
    autoscale: false
    maxReplicas: 10
    cpuThreshold: 75
    image:
      repository: ibmstocktrader/tradr
      tag: latest
  twitter:
    accessToken: 919153883989073920-j9nyQarVpSqOSQsSoe5e6uEg44eNdmJ
    accessTokenSecret: KT4gAahSi19NVFCxa2KAEkDyFKhtbsdxuF5iCHRySclJ2
    consumerKey: 4Z6yvehoJllFwserpEikjjkBL
    consumerSecret: in2WtPoCgn6SZKn1JCwacY3enRbh3aqUWrltEEOcW2MVWfi5ho
  watson:
    id: apikey
    passwordOrApiKey: enY7b5sUl5fcgpF37zK2d83qGmKYRoKFJGKm1P_9-tJ5
    url: https://api.us-south.tone-analyzer.watson.cloud.ibm.com/instances/195be178-5f78-467f-8355-99ee5772f4c2/v3/tone?version=2017-09-21&sentences=false
